name: "bench"
on:
  push:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'build with docker'
      run: |
        docker build -t fluent-plugin-s3-arrow .
    - name: 'bench'
      id: 'bench'
      run: |
        docker run fluent-plugin-s3-arrow /bin/bash -c "benchmark-driver benchmark/compress.yml -o markdown" | tee benchmark.md
    - uses: actions/upload-artifact@v2
      with:
        name: benchmark.md
        path: benchmark.md
    - name: 'bench memory'
      id: 'bench_mem'
      run: |
        docker run fluent-plugin-s3-arrow /bin/bash -c "benchmark-driver benchmark/compress.yml --runner memory"
